<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Shortlist</name>
   <tag></tag>
   <elementGuidId>b8839ac8-1bbc-4649-a0b7-0b58304fc3b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' oxd-button--success ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.oxd-button--success</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d6c53bc8-3674-4da4-96ab-e0c62eb1dcd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0b0d338b-ffbb-4640-959a-33820dde3458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oxd-button oxd-button--medium oxd-button--success</value>
      <webElementGuid>451fae50-103c-4faa-8d10-69dda75eaced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Shortlist </value>
      <webElementGuid>8ce68993-6b4a-41db-8f50-448fe8fa1bf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-9d8e3550ea1fcd65d0e6990444efee86</value>
      <webElementGuid>997deb22-4c19-4518-9084-e8e23bf310e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' oxd-button--success ')]</value>
      <webElementGuid>1615b00f-8a03-4757-9aa5-301f1dcbbf42</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' oxd-button--success ')]</value>
      <webElementGuid>bd2aadfa-2ac7-441d-8ae1-dcd4d8d5e412</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = ' Shortlist ' or . = ' Shortlist ')]</value>
      <webElementGuid>3eba7ebf-7173-41fa-a09c-a660f66b4179</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
