<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_oxd-file-input</name>
   <tag></tag>
   <elementGuidId>1b759413-7a51-42a8-993a-356c6b18ae57</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' oxd-file-input ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.oxd-file-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f06e755c-117b-48c8-87af-d09be33348ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>c6c33ea8-ec04-47ff-b75a-c75de8e84ea9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oxd-file-input</value>
      <webElementGuid>a6dcc4c7-8ac9-4847-878f-f8e97d39c675</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-22297ec7ca1036b33fed33019f9d0f67</value>
      <webElementGuid>989b339f-4d9a-4551-a9ac-cea876cd9038</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' oxd-file-input ')]</value>
      <webElementGuid>ac32be45-12a1-402a-9a07-64e01dc431f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' oxd-file-input ')]</value>
      <webElementGuid>bee647f3-88bf-4b4f-8ed0-13368393cac5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file']</value>
      <webElementGuid>05945d74-3243-4a91-9bcc-4aa4e7ea00d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
